<?php
/**
 * Created by PhpStorm.
 * User: fan
 * Date: 6/6/16
 * Time: 17:14
 */

namespace frontend\models\blog;
use yii\db\ActiveRecord;
use yii;

class Article extends ActiveRecord
{
    public static function getDb()
    {
        //return parent::getDb(); // TODO: Change the autogenerated stub
        return yii::$app->myblogDB;
    }

    public static function tableName()
    {
        return 't_article';
    }
}
