<?php
/**
 * Created by PhpStorm.
 * User: fan
 * Date: 5/22/16
 * Time: 22:39
 */
namespace frontend\models\testCountry;
use yii\db\ActiveRecord;

class Country extends ActiveRecord
{

    public static function getDb()
    {
        //return parent::getDb(); // TODO: Change the autogenerated stub
        return \yii::$app->countryDB;
    }

    public static function getCountries()
    {
        return self::find()->count('*');
    }
}